/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Service.Implement.ThitService;
import ViewModels.ThitView;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tus
 */
public class Thit extends javax.swing.JFrame {

    ThitView tv = new ThitView();
    private ThitService service = new ThitService();

    public Thit() {
        initComponents();
        setLocationRelativeTo(null);
        this.taiDuLieu();
    }

    private void taiDuLieu() {
        txtMa.setText("");
        txtTen.setText("");
        buttonGroup1.clearSelection();
        DefaultTableModel model = (DefaultTableModel) this.tblThit.getModel();
        model.setRowCount(0);
        ArrayList<ThitView> list = (ArrayList<ThitView>) this.service.getAll();
        for (ThitView x : list) {
            Object[] rowData = {
                x.getId(), x.getMa(), x.getTen(),x.getIdLT(),x.getTrangthai()
            };
            model.addRow(rowData);
        }
    }

    private boolean errorTextField(JTextField jTextField, String mess) {
        JOptionPane.showMessageDialog(this, mess);
        jTextField.selectAll();
        jTextField.requestFocus();
        return false;
    }

    private boolean validation() {
        String s = txtMa.getText().trim();

        if (s.equals("")) {
            return errorTextField(txtMa, "Vui lòng nhập mã hộp thịt");
        }

        s = txtTen.getText().trim();
        if (s.equals("")) {
            return errorTextField(txtTen, "Vui lòng nhập tên hộp thịt");
        }
                s = txtTen.getText().trim();
        if (s.equals("")) {
            return errorTextField(txtTen, "Vui lòng nhập tên hộp thịt");
        }

        if (!rdoConHang.isSelected() && !rdohetHang.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn trạng thái");
            return false;
        }

        return true;
    }

    private ThitView getForm() {
        String id = this.LBID.getText();
        String ma = this.txtMa.getText();
        String ten = this.txtTen.getText();
        String maLT = this.txtMaLT.getText();
        int trangthai = this.rdoConHang.isSelected() ? 0 : 1;
        ThitView vw = new ThitView(id, ma, ten,maLT, trangthai);
        return vw;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LBID = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        rdoConHang = new javax.swing.JRadioButton();
        rdohetHang = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThit = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtMaLT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 27, -1, -1));

        jLabel2.setText("Mã:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Tên Thịt:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 77, 61, -1));

        jLabel5.setText("Trạng Thái:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 144, -1, -1));

        LBID.setText("--");
        getContentPane().add(LBID, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 27, 25, -1));

        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 47, 81, -1));
        getContentPane().add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 74, 81, -1));

        buttonGroup1.add(rdoConHang);
        rdoConHang.setText("Còn hàng");
        getContentPane().add(rdoConHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 140, -1, -1));

        buttonGroup1.add(rdohetHang);
        rdohetHang.setText("Hết hàng");
        getContentPane().add(rdohetHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 140, -1, -1));

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 73, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 99, 59, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 47, 59, -1));

        tblThit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Mã", "Tên thịt", "loại thịt", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblThit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThit);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 390, 138));

        jLabel4.setText("Mã Loại Thịt:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, -1, -1));
        getContentPane().add(txtMaLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 100, 81, -1));

        jButton1.setText("...");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 103, 20, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (!validation()) {
            return;
        }
        int chon = JOptionPane.showConfirmDialog(this, "Xác Nhận Thêm Thịt");
        if (chon == JOptionPane.YES_OPTION) {
            if (service.add(this.getForm())) {
                JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                this.taiDuLieu();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm Thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hủy Thêm Thành Công");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblThitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThitMouseClicked
        int row = tblThit.getSelectedRow();
        txtMa.setText(tblThit.getValueAt(row, 1).toString());
        txtTen.setText(tblThit.getValueAt(row, 2).toString());
        txtMaLT.setText(tblThit.getValueAt(row, 3).toString());
        
        String check = tblThit.getValueAt(row, 4).toString();
        
        if (Integer.parseInt(check) > 0) {
            rdoConHang.setSelected(true);
        } else {
            rdohetHang.setSelected(true);
        }
    }//GEN-LAST:event_tblThitMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblThit.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thịt cần sửa");
            return;
        }
        if (!validation())
            return;
        if (this.service.update(getForm())) {
            this.taiDuLieu();
            JOptionPane.showMessageDialog(this, "Sửa thịt thành công");
        } else
            JOptionPane.showMessageDialog(this, "Sửa thịt thất bại");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblThit.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thịt cần xóa");
            return;
        }
        if (this.service.delete(getForm())) {
            this.taiDuLieu();
            JOptionPane.showMessageDialog(this, "Xóa thịt thành công");
        } else
            JOptionPane.showMessageDialog(this, "Xóa thịt thất bại");
    }//GEN-LAST:event_btnXoaActionPerformed

    private ThitView getThitFromForm() {
        return new ThitView(null, txtMa.getText(), txtTen.getText(),txtMaLT.getText(), rdoConHang.isSelected() ? 1 : 0);
    }

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemMouseClicked

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new LoaiThit().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBID;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoConHang;
    private javax.swing.JRadioButton rdohetHang;
    private javax.swing.JTable tblThit;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaLT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
